# Primary predictive model for the project.
#
# The discovery normalization artifact generated by the project run is used as
# the common project input.
# Feature screening and scaling are fitted inside each training split; the
# external cohort labels are not used for model
# selection. Set CAD_DISCOVERY_ROOT to the current run's normalization folder
# when this script is called by code/run_project.R.

command_args <- commandArgs(trailingOnly = FALSE)
file_arg <- command_args[grepl("^--file=", command_args)]
if (length(file_arg) != 1) stop("Run this script with Rscript code/50_nested_cv_signature.R")
script_dir <- dirname(normalizePath(sub("^--file=", "", file_arg)))
source(file.path(script_dir, "00_config.R"))

suppressPackageStartupMessages({
  library(glmnet)
  library(pROC)
})

set.seed(20260922)
out_root <- file.path(output_root, "50_nested_cv_signature")
if (dir.exists(out_root)) {
  unlink(list.files(out_root, full.names = TRUE, all.files = TRUE, no.. = TRUE), recursive = TRUE, force = TRUE)
}
dir.create(out_root, recursive = TRUE, showWarnings = FALSE)

discovery_root <- Sys.getenv("CAD_DISCOVERY_ROOT", unset = file.path(output_root, "20_full_experiment", "01_normalize"))
discovery_expr_path <- file.path(discovery_root, "merged.before_combat.txt")
discovery_meta_path <- file.path(discovery_root, "metadata.txt")
if (!file.exists(discovery_expr_path) || !file.exists(discovery_meta_path)) {
  stop("Project discovery artifacts are missing: ", discovery_expr_path, " and/or ", discovery_meta_path)
}
expr <- as.matrix(read_expression(discovery_expr_path))
meta <- read.table(discovery_meta_path, header = TRUE, sep = "\t", stringsAsFactors = FALSE, check.names = FALSE)
if (!all(meta$sample %in% colnames(expr))) stop("Metadata samples are missing from the expression matrix.")
expr <- expr[, meta$sample, drop = FALSE]
y <- ifelse(meta$group == "Treat", 1, 0)
if (anyNA(expr) || any(!is.finite(expr))) stop("Expression matrix contains missing or non-finite values.")
strata <- interaction(meta$dataset, meta$group, drop = TRUE)
if (any(table(strata) < 5)) stop("Each dataset/group stratum needs at least 5 samples.")

# Constrain the deployable model to genes that have a known probe mapping
# in the fixed GSE113079 GPL20115 annotation. This uses platform metadata only,
# never external labels, and prevents a final model that cannot be applied.
split_gene_symbols <- function(x) {
  if (is.na(x) || !nzchar(x) || x %in% c("NA", "None")) return(character(0))
  trimws(unlist(strsplit(x, "[,;|/]+")))
}
external_platform <- read.delim(paths$gse113079_platform, skip = 41, header = TRUE, sep = "\t", quote = "", comment.char = "", fill = TRUE, stringsAsFactors = FALSE, check.names = FALSE)
external_symbols <- unique(unlist(lapply(external_platform$GeneSymbol, split_gene_symbols)))
deployable_genes <- intersect(rownames(expr), external_symbols)
max_screen_genes <- 100L
if (length(deployable_genes) < max(100L, 2L * max_screen_genes)) stop("Too few genes have fixed external-platform mappings.")
expr <- expr[deployable_genes, , drop = FALSE]
writeLines(deployable_genes, file.path(out_root, "candidate_gene_universe.txt"))

alpha_grid <- c(0, 0.25, 0.5, 0.75, 1)
outer_k <- 5L
inner_k <- 3L

stratified_folds <- function(strata, k) {
  fold <- integer(length(strata))
  for (s in levels(factor(strata))) {
    idx <- which(strata == s)
    idx <- sample(idx, length(idx))
    fold[idx] <- rep(seq_len(k), length.out = length(idx))
  }
  fold
}

screen_genes <- function(x, response, n = max_screen_genes) {
  positive <- response == 1
  negative <- response == 0
  n_positive <- sum(positive)
  n_negative <- sum(negative)
  mean_difference <- rowMeans(x[, positive, drop = FALSE]) - rowMeans(x[, negative, drop = FALSE])
  variance_positive <- apply(x[, positive, drop = FALSE], 1, var)
  variance_negative <- apply(x[, negative, drop = FALSE], 1, var)
  statistic <- abs(mean_difference) / sqrt(variance_positive / n_positive + variance_negative / n_negative)
  statistic[!is.finite(statistic)] <- 0
  names(statistic) <- rownames(x)
  names(sort(statistic, decreasing = TRUE))[seq_len(min(n, length(statistic)))]
}

fit_scaler <- function(x) {
  center <- colMeans(x)
  scale_value <- apply(x, 2, sd)
  scale_value[!is.finite(scale_value) | scale_value == 0] <- 1
  list(center = center, scale = scale_value)
}

apply_scaler <- function(x, scaler) {
  sweep(sweep(x, 2, scaler$center, "-"), 2, scaler$scale, "/")
}

fit_penalized <- function(x, response, alpha, foldid) {
  cv.glmnet(
    x = x, y = response, family = "binomial", alpha = alpha,
    type.measure = "auc", foldid = foldid, standardize = FALSE,
    nlambda = 100, control = list(maxit = 200000)
  )
}

roc_auc <- function(response, score) {
  as.numeric(auc(roc(response, score, levels = c(0, 1), direction = "<", quiet = TRUE)))
}

pr_auc <- function(response, score) {
  order_index <- order(score, decreasing = TRUE)
  truth <- response[order_index] == 1
  true_positive <- cumsum(truth)
  false_positive <- cumsum(!truth)
  recall <- true_positive / sum(truth)
  precision <- true_positive / (true_positive + false_positive)
  sum(diff(c(0, recall)) * precision)
}

inner_alpha_auc <- function(x_outer, y_outer, strata_outer, alpha) {
  inner_folds <- stratified_folds(strata_outer, inner_k)
  fold_auc <- numeric(inner_k)
  for (inner_fold in seq_len(inner_k)) {
    train_idx <- which(inner_folds != inner_fold)
    valid_idx <- which(inner_folds == inner_fold)
    genes <- screen_genes(x_outer[, train_idx, drop = FALSE], y_outer[train_idx])
    train_matrix <- t(x_outer[genes, train_idx, drop = FALSE])
    valid_matrix <- t(x_outer[genes, valid_idx, drop = FALSE])
    scaler <- fit_scaler(train_matrix)
    train_matrix <- apply_scaler(train_matrix, scaler)
    valid_matrix <- apply_scaler(valid_matrix, scaler)
    inner_inner_folds <- stratified_folds(strata_outer[train_idx], inner_k)
    fit <- fit_penalized(x = train_matrix, response = y_outer[train_idx], alpha = alpha, foldid = inner_inner_folds)
    prediction <- as.numeric(predict(fit, newx = valid_matrix, s = "lambda.1se", type = "response"))
    fold_auc[inner_fold] <- roc_auc(y_outer[valid_idx], prediction)
  }
  mean(fold_auc)
}

outer_folds <- stratified_folds(strata, outer_k)
outer_predictions <- vector("list", outer_k)
outer_metrics <- vector("list", outer_k)
inner_scores <- vector("list", outer_k)
selected_genes <- vector("list", outer_k)
model_selected_genes <- vector("list", outer_k)

for (outer_fold in seq_len(outer_k)) {
  train_idx <- which(outer_folds != outer_fold)
  test_idx <- which(outer_folds == outer_fold)
  scores <- vapply(alpha_grid, function(alpha) {
    inner_alpha_auc(expr[, train_idx, drop = FALSE], y[train_idx], strata[train_idx], alpha)
  }, numeric(1))
  best_alpha <- alpha_grid[which.max(scores)]
  inner_scores[[outer_fold]] <- data.frame(outer_fold = outer_fold, alpha = alpha_grid, inner_auc = scores)

  genes <- screen_genes(expr[, train_idx, drop = FALSE], y[train_idx])
  selected_genes[[outer_fold]] <- genes
  train_matrix <- t(expr[genes, train_idx, drop = FALSE])
  test_matrix <- t(expr[genes, test_idx, drop = FALSE])
  scaler <- fit_scaler(train_matrix)
  train_matrix <- apply_scaler(train_matrix, scaler)
  test_matrix <- apply_scaler(test_matrix, scaler)
  foldid <- stratified_folds(strata[train_idx], inner_k)
  fit <- fit_penalized(train_matrix, y[train_idx], best_alpha, foldid)
  prediction <- as.numeric(predict(fit, newx = test_matrix, s = "lambda.1se", type = "response"))
  coefficient <- as.numeric(coef(fit, s = "lambda.1se"))
  selected <- rownames(coef(fit, s = "lambda.1se"))[coefficient != 0]
  selected <- setdiff(selected, "(Intercept)")
  model_selected_genes[[outer_fold]] <- selected
  outer_predictions[[outer_fold]] <- data.frame(
    sample = meta$sample[test_idx], dataset = meta$dataset[test_idx], group = meta$group[test_idx],
    outer_fold = outer_fold, probability = prediction, stringsAsFactors = FALSE
  )
  outer_metrics[[outer_fold]] <- data.frame(
    outer_fold = outer_fold, n = length(test_idx), alpha = best_alpha,
    auc = roc_auc(y[test_idx], prediction), pr_auc = pr_auc(y[test_idx], prediction),
    selected_model_genes = length(selected), stringsAsFactors = FALSE
  )
}

outer_predictions <- do.call(rbind, outer_predictions)
outer_predictions <- outer_predictions[match(meta$sample, outer_predictions$sample), , drop = FALSE]
outer_metrics <- do.call(rbind, outer_metrics)
inner_scores <- do.call(rbind, inner_scores)
screened_table <- do.call(rbind, lapply(seq_along(selected_genes), function(i) {
  data.frame(outer_fold = i, Gene = selected_genes[[i]], stringsAsFactors = FALSE)
}))
screen_frequency <- as.data.frame(table(screened_table$Gene), stringsAsFactors = FALSE)
colnames(screen_frequency) <- c("Gene", "outer_screen_frequency")
screen_frequency$frequency <- screen_frequency$outer_screen_frequency / outer_k
model_table <- do.call(rbind, lapply(seq_along(model_selected_genes), function(i) {
  data.frame(outer_fold = i, Gene = model_selected_genes[[i]], stringsAsFactors = FALSE)
}))
model_frequency <- if (nrow(model_table)) {
  value <- as.data.frame(table(model_table$Gene), stringsAsFactors = FALSE)
  colnames(value) <- c("Gene", "outer_model_selection_frequency")
  value$frequency <- value$outer_model_selection_frequency / outer_k
  value
} else data.frame(Gene = character(), outer_model_selection_frequency = integer(), frequency = numeric())

outer_auc <- roc_auc(y, outer_predictions$probability)
outer_pr_auc <- pr_auc(y, outer_predictions$probability)

# Freeze one final discovery model only after the nested assessment is complete.
mean_alpha <- aggregate(inner_auc ~ alpha, data = inner_scores, FUN = mean)
final_alpha <- mean_alpha$alpha[which.max(mean_alpha$inner_auc)]
final_genes <- screen_genes(expr, y)
final_train <- t(expr[final_genes, , drop = FALSE])
final_scaler <- fit_scaler(final_train)
final_train <- apply_scaler(final_train, final_scaler)
final_foldid <- stratified_folds(strata, inner_k)
final_fit <- fit_penalized(final_train, y, final_alpha, final_foldid)
final_coefficient <- as.matrix(coef(final_fit, s = "lambda.1se"))
final_coefficients <- data.frame(Gene = rownames(final_coefficient), coefficient = as.numeric(final_coefficient[, 1]), stringsAsFactors = FALSE)
final_nonzero_genes <- final_coefficients$Gene[final_coefficients$Gene != "(Intercept)" & final_coefficients$coefficient != 0]

write.table(data.frame(sample = meta$sample, dataset = meta$dataset, group = meta$group, outer_fold = outer_folds), file.path(out_root, "fold_assignments.tsv"), sep = "\t", quote = FALSE, row.names = FALSE)
write.table(outer_predictions, file.path(out_root, "outer_predictions.tsv"), sep = "\t", quote = FALSE, row.names = FALSE)
write.table(outer_metrics, file.path(out_root, "outer_metrics.tsv"), sep = "\t", quote = FALSE, row.names = FALSE)
write.table(inner_scores, file.path(out_root, "inner_alpha_scores.tsv"), sep = "\t", quote = FALSE, row.names = FALSE)
write.table(screen_frequency, file.path(out_root, "screened_gene_frequency.tsv"), sep = "\t", quote = FALSE, row.names = FALSE)
write.table(model_frequency, file.path(out_root, "model_gene_frequency.tsv"), sep = "\t", quote = FALSE, row.names = FALSE)
write.table(final_coefficients, file.path(out_root, "final_coefficients.tsv"), sep = "\t", quote = FALSE, row.names = FALSE)
write.table(data.frame(Gene = names(final_scaler$center), center = unname(final_scaler$center), scale = unname(final_scaler$scale)), file.path(out_root, "final_preprocessing_params.tsv"), sep = "\t", quote = FALSE, row.names = FALSE)
write.table(data.frame(metric = c("outer_oof_auc", "outer_oof_pr_auc", "final_alpha", "candidate_gene_count", "final_screen_gene_count", "final_nonzero_gene_count"), value = c(outer_auc, outer_pr_auc, final_alpha, length(deployable_genes), length(final_genes), length(final_nonzero_genes))), file.path(out_root, "summary.tsv"), sep = "\t", quote = FALSE, row.names = FALSE)
writeLines(capture.output(sessionInfo()), file.path(out_root, "sessionInfo.txt"))
writeLines(c(
  "Primary discovery-cohort predictive model.",
  "Feature screening is repeated in each inner/outer training split; model nonzero-gene frequencies are recorded separately.",
  "Elastic Net alpha is selected by inner cross-validation; lambda.1se is used.",
  "Scaling is fitted on each training split and applied unchanged to its validation split.",
  paste("Discovery matrix:", discovery_expr_path),
  "The discovery normalization artifact generated in this run is used because ComBat has no general frozen predict method.",
  paste("Candidate genes restricted to fixed GPL20115 mapping:", length(deployable_genes)),
  "GSE113079 labels were not used for feature, hyperparameter, or preprocessing selection.",
  paste("Outer OOF ROC-AUC:", sprintf("%.4f", outer_auc)),
  paste("Outer OOF PR-AUC:", sprintf("%.4f", outer_pr_auc))
), file.path(out_root, "RUN_METADATA.txt"))
cat(sprintf("Nested CV signature assessment written to %s\nOuter OOF ROC-AUC: %.4f; PR-AUC: %.4f\n", out_root, outer_auc, outer_pr_auc))
